### ISSUE TITLE
apply for account

### ISSUE THREAD

**Issue by lvxiaoqian555** [10x-Engineers/riscv-ci-partners#24]
Hi

According to the guide https://10x-engineers.github.io/riscv-ci-partners/Software_Developer_Guide/ 
I want to apply a new account to login the Jenkins

Here is my information:
Name：xiaoqian lv
Contact Email: lvxiaoqian@iscas.ac.cn
URL of the GitHub project repository: https://github.com/lvxiaoqian555/for_test.git
Name of your organization: ISCAS

Thank you in advance
Hope to hear from you

**Comment by alitariq4589** [comment]
Hi @lvxiaoqian555 ,  
First of all I am very sorry for not getting in contact with you sooner as I had not set myself to watch the repository and this issue was not assigned. We are very glad to see you want to get in touch with our cloud environment. I have sent you an email with credentials to access cloud-v environment at <https://cloud-v.co>. If you have any query, please don't hesitate to ask.

**Comment by alitariq4589** [comment]
Hi @lvxiaoqian555 ,
Dont forget to ping me up once you have added github credentials in Cloud-V. Also, please share with me credentials ID via email. I will need that so that jenkins job build may interact with github.
